---
title: "BOQ Test"
output: 
  html_notebook


params:
  AOC: "44087724"
  reference_sites: ["44007727", 
                    "43557712",
                    "43497905",
                                     "43117922",
                                     "43397900",
                                     "43517847",
                                     "43527851",
                                     "44397535",
                                     "43557717",
                                     "43527856"]
  restrict_threshold: 8
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("Scripts/setup.R")
ref_sites = params$reference_sites
interest_species = params$interest_species
ref_names = get_waterbody_names(cons_data, site_id = ref_sites)
aoc_id = params$AOC



aoc_name = get_waterbody_names(cons_data, site_id = aoc_id)


# Make table
t1_df = make_restrict_table(cons_data,
                                aoc_id,
                                length_levels)
# Set contaminant mappings
unique_contaminants <- extract_unique_adv_causes(t1_df)
mappings <- assign_contaminant_mappings(unique_contaminants)
contaminant_shapes <- mappings$shapes
contaminant_colours <- mappings$colours


```



```{r}

render_t1_table(
  df = t1_df,
  length_levels = length_levels,
  contaminant_shapes = contaminant_shapes,
  contaminant_colours = contaminant_colours,
  table_height = "1400px",
  show_legend = TRUE,
  interest_species = interest_species
)
```
```{r Test pass/fail output T1}
report_pass_fail_species(flags, tier = "t1", output = "table")
```
The following species pass/fail Tier 1:

`r report_pass_fail_species(flags, tier = "t1", output = "list")`


```{r Tier 2}
t2_table <- render_t2_table(cons_data = cons_data,
                            aoc_id = aoc_id,
                            reference_sites = ref_sites,
                            length_levels = length_levels,
                            interest_species = NULL
)

t2_table

```

```{r}
flags <- get_species_pass_flags(cons_data, aoc_id, ref_sites, length_levels)

report_pass_fail_species(flags, tier = "t1", output = "list")
# ... show Tier 1 table ...

report_pass_fail_species(flags, tier = "t2")
# ... show Tier 2 table ...

report_pass_fail_species(flags, tier = "both", output = "table")

```

